### ISSUE TITLE
Failure when scanning a domain with 10k+ certificates

### ISSUE THREAD

**Issue by christophetd** [christophetd/censys-subdomain-finder#1]
Reported by @soaj1664ashar. See: https://pbs.twimg.com/media/DTqhtmsX0AAYlkb.jpg

Potential solutions: 
- Paginate the search (i.e. make several API requests reading less than 10k certificates)
- Truncate to 10k search results using the Censys API [`max_results`](https://github.com/censys/censys-python/blob/master/censys/base.py#L157) parameter

**Comment by wangoloj** [comment]
This could be an issue with rate-limiting in outbound response with censys, 
Ensure that your account is not in rate-limit imposed on your  API account.
Though like google is has I found it has over 31291 subdomains using this [tools](https://www.nmmapper.com/sys/tools/subdomainfinder/), when I tried censys it failed.

**Comment by christophetd** [comment]
should be done in #14, limited to 1k subdomains by default now
