### ISSUE TITLE
ImportError: No module named censys.search

### ISSUE THREAD

**Issue by welltest** [christophetd/censys-subdomain-finder#17]
![2022-08-21 23_48_53-christophetd_censys-subdomain-finder_ ⚡ Perform subdomain enumeration using the ](https://user-images.githubusercontent.com/7748482/185805246-f9e3807a-9b4b-4e84-857a-6993f532d264.png)

```
python3 -m venv venv
source venv/bin/activate
python censys-subdomain-finder.py example.com
```
But this is working,

**Comment by christophetd** [comment]
You need to install the requirements after having enabled the venv, c.f. the readme
 
``` 
pip install -r requirements.txt
```
