### ISSUE TITLE
not config apis

### ISSUE THREAD

**Issue by halfstar1** [christophetd/censys-subdomain-finder#19]
[*] Applying non-commerical limits (1000 results at most)
[!] Please set your Censys API ID and secret from your environment (CENSYS_API_ID and CENSYS_API_SECRET) or from the command line.

**Comment by christophetd** [comment]
You need to set your Censys API keys, c.f. the readme:

```
export CENSYS_API_ID=...
export CENSYS_API_SECRET=...
```
