### ISSUE TITLE
ModuleNotFoundError: No module named 'censys'

### ISSUE THREAD

**Issue by gopinath6** [christophetd/censys-subdomain-finder#2]
May i what am missing?

$ pip install requirements.txt
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions:                                                                                                                                       )
No matching distribution found for requirements.txt

$ python censys_subdomain_finder.py example.com
Traceback (most recent call last):
  File "censys_subdomain_finder.py", line 3, in <module>
    import censys.certificates
ModuleNotFoundError: No module named 'censys'

**Comment by christophetd** [comment]
You're missing an `-r` in the install command:

```
$ pip install -r requirements.txt
```

**Comment by gopinath6** [comment]
thanks!

**Comment by El-t0ro** [comment]
hey i am getting the same error , any solution?
thanks

**Comment by christophetd** [comment]
Did you try `pip install -r requirements.txt`?

**Comment by DarkCodeOrg** [comment]
hey i tried with -r even after that i am getting a error that   no module named censys.certificates

**Comment by Jerry-1337** [comment]
me too..
ModuleNotFoundError: No module named 'censys.certificates'

**Comment by Shahad7278** [comment]
me too..
ModuleNotFoundError: No module named 'censys.certificates'

**Comment by christophetd** [comment]
Can you provide the exact sequence of command you ran, and your Python version? The following is expected to work:

```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```
